apiVersion: v1
kind: Service
metadata:
  name: pinger-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: pinger
  ports:
    - protocol: TCP
      port: 50050
      targetPort: 50050
